const API_DRAWING_URL_DEVELOPMENT = 'https://localhost:7039';
const API_USER_URL_DEVELOPMENT = 'https://localhost:7100';
const API_TOKEN_URL_DEVELOPMENT = 'https://localhost:7100';

const ENDPOINTS = {
    GET_ALL_DRAWINGS: 'api/Drawing',
    GET_DRAWING_BY_ID: 'api/Drawing',
    GET_DRAWING_BY_PARAMETERS: 'api/Drawing/page',
    CREATE_DRAWING: 'api/Drawing',
    UPDATE_DRAWING: 'api/Drawing',
    DELETE_DRAWING: 'api/Drawing',
    GET_ALL_USERS: 'api/User',
    GET_USER_BY_ID: 'api/User',
    CREATE_USER: 'api/User',
    UPDATE_USER: 'api/User',
    DELETE_USER: 'api/User',
    POST_LOGIN: 'api/token',
    REFRESH_TOKEN: 'api/token/refresh-token',
};

const development = {
    API_URL_GET_ALL_DRAWINGS:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_DRAWINGS}`,
    API_URL_GET_DRAWING_BY_ID:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.GET_DRAWING_BY_ID}`,
    API_URL_GET_DRAWING_BY_PARAMETERS:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.GET_DRAWING_BY_PARAMETERS}`,
    API_URL_CREATE_DRAWING:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_DRAWING}`,
    API_URL_UPDATE_DRAWING:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_DRAWING}`,
    API_URL_DELETE_DRAWING:`${API_DRAWING_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_DRAWING}`,
    API_URL_GET_ALL_USERS:`${API_USER_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USERS}`,
    API_URL_GET_USER_BY_ID:`${API_USER_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_CREATE_USER:`${API_USER_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_USER}`,
    API_URL_UPDATE_USER:`${API_USER_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER:`${API_USER_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER}`,
    API_URL_POST_LOGIN:`${API_TOKEN_URL_DEVELOPMENT}/${ENDPOINTS.POST_LOGIN}`,
    API_URL_REFRESH_TOKEN:`${API_TOKEN_URL_DEVELOPMENT}/${ENDPOINTS.REFRESH_TOKEN}`,
    TOKEN_TYPE:`Bearer`,
};

const production = development;//temp

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;
